# Generated by Django 5.2.6 on 2025-10-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog_image/default_error.png', null=True, upload_to='blog_image/%Y/%m/%d/'),
        ),
    ]
